# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectTitle', models.CharField(max_length=500)),
                ('subjectDesc', models.CharField(max_length=5000)),
                ('pubDate', models.DateTimeField(verbose_name='Date Published')),
            ],
        ),
    ]
